[package]
name = "wsdl-rs"
version = "0.1.0"
authors = ["Jakko Sikkar <jakko.sikkar@gmail.com>"]

[[bin]]
name = "wsdl"
path = "src/bin/main.rs"

[lib]
name = "wsdl"
path = "src/wsdl/lib.rs"

[dependencies]
hyper = "0.9.9"
xml-rs = "0.3.4"
encoding = "0.2.32"
uchardet = "1.0.0"